version: 3.9

services:
  postgres:
    container_name: postgresql
    image: postgres:${POSTGRES_VERSION}
    hostname: postgresql
    restart: always
    security_opt:
      - no-new-privileges: true
    pids_limit: 100
    read_only: true
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/config:/etc/postgresql
      - ./postgresql/wal_archive:/var/lib/postgresql/archive
      - ./postgresql/logs:/var/log/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - communication
  mattermost:
    depends_on:
      - postgres
    container_name: mattermost
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_VERSION}
    hostname: mattermost
    restart: always
    security_opt:
      - no-new-privileges: true
    pids_limit: 200
    volumes:
      - ./mattermost/config:/mattermost/config
      - ./mattermost/data:/mattermost/data
      - ./mattermost/logs:/mattermost/logs
      - ./mattermost/plugins:/mattermost/plugins
      - ./mattermost/client/plugins:/mattermost/client/plugins
      - ./mattermost/bleve-indexes:/mattermost/bleve-indexes
    environment:
      - TZ
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE
      - MM_BLEVESETTINGS_INDEXDIR
      - MM_SERVICESETTINGS_SITEURL
    networks:
      - communication
  nginx:
    depends_on:
      - mattermost
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    hostname: nginx
    restart: always
    environment:
      -	TZ
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - communication
networks:
  communication:
    name: communication
